apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-system
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: oidc-http
      port: 80
      targetPort: 8008
      protocol: TCP
  selector:
    app: spire-server
