apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-system
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: oidc-discovery
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: spire-server
